name: "setup-llvm"
description: "Install LLVM 20 + related tools (with caching). Accepts a space-separated list of apt packages."
inputs:
  packages:
    description: "Space-separated apt packages to install (default includes libc++, clang, lld, lldb, jq)"
    required: false
    default: "libc++-20-dev libc++abi-20-dev clang-20 lld-20 lldb-20 jq"

runs:
  using: "composite"
  steps:
    - name: Cache LLVM 20 + libc++
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          /usr/lib/llvm-20
          /usr/bin/clang-20
          /usr/bin/clang++-20
          /usr/bin/lld-20
          /usr/bin/lldb-20
        key: llvm-20-ubuntu-${{ runner.arch }}-2025-v5
        restore-keys: |
          llvm-20-ubuntu-${{ runner.arch }}-
          llvm-20-ubuntu-
          llvm-20-

    - name: Install LLVM toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget gnupg ca-certificates lsb-release software-properties-common
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/apt-llvm.gpg
        echo "deb [signed-by=/usr/share/keyrings/apt-llvm.gpg] https://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-20 main" | sudo tee /etc/apt/sources.list.d/apt-llvm.org.list > /dev/null
        sudo apt-get update
